### ISSUE TITLE
Page titles are static

### ISSUE THREAD

**Issue by usrme** [MartinHeinz/blog-frontend#6]
First off, thanks for all the wonderful material you put out!

Secondly, when opening any of the pages on your website the title always reads **Martin Heinz - Personal Website & Blog**, which wouldn't be too much of an issue if one were just contained to the non-blog portion of your website, but when opening a blog post (e.g. https://martinheinz.dev/blog/43) the title reads the same as always. This makes storing your posts in Pocket or bookmarking otherwise a bit of a chore as someone then has to manually edit the entry (if it can even be done, which isn't possible in Pocket) to be able to make sense of the entry in a list.

A friend of mine (shout-out @andreasvirkus) pointed me towards [this option](https://github.com/MartinHeinz/blog-frontend/blob/master/src/main.js#L97) in your Vue code as the possible culprit in this.

Would you consider making the necessary changes to properly tie page titles to whatever the actual title is? Having readable slugs (e.g. https://martinheinz.dev/blog/advanced-git-features-you-didnt-know-you-needed) would also improve things greatly in my eyes, but that's just icing on the :cake:.

**Comment by MartinHeinz** [comment]
Hi, thanks for creating the issue and sorry for the terribly slow response.

I fixed it and titles should update correctly now (see: https://github.com/MartinHeinz/blog-frontend/commit/9d7ba0afbd79176da7b7f3afcda0da052105846d)

As for the readable slugs... that will task for another day. :smile:
